#!/bin/bash
DATE=$(date +%F-%H-%M-%S)
SCRIPT_NAME=$0
LOGFILE=/tmp/$SCRIPT_NAME-$DATE.log
USERID=$(id -u)
R="\e[31m"
G="\e[32m"
N="\e[0m"
Y="\e[33m"
#This function should validate the previous command and inform the user if it is success or not
VALIDATE(){
    # $1 will be the argument passed from the command line from the below code to this function
if [ $1 -ne 0 ]
then
    echo -e "$R $2 : installation is failure"
    exit 1
else
    echo -e "$G $2 :  successfully installed"
fi
}

for VARIABLE in $@
do
 yum list installed $VARIABLE
 if [ $? -ne 0 ]
 then 
   echo "$VARIABLE is not installed ,let's install "
   yum install $VARIABLE -y &>>$LOGFILE
   VALIDATE $VALIDATE "$VARIABLE"
 else
   echo -e  "$Y $VARIABLE is already installed $N"
 fi
done
